---
- name: GENERATE OS REPORT FROM ROUTERS
  hosts: cisco
  connection: network_cli
  gather_facts: no

  tasks:
    - name: GATHER ROUTER FACTS
      ios_facts:

    - name: RENDER FACTS AS A REPORT USING JINJA2 template
      template:
        src: /routerinfo/template/os_report.j2
        dest: /routerinfo/reports/{{ inventory_hostname }}.md

    - name: CONSOLIDATE THE IOS DATA
      assemble:
        src: /routerinfo/reports
        dest: //routerinfo/network_os_report.md
      delegate_to: localhost
      run_once: yes
