- name: GENERATE OS REPORT FROM ROUTERS
  hosts: cisco-router-1
  connection: network_cli
  gather_facts: no

  tasks:
    - name: Run ping to rtr4
      register: ping_result
      ios_ping:
        dest: "{{ item }}"
        state: present
      with_items:
        - 10.0.4.4
        - 10.0.3.4
        - 10.0.5.4
